/*
 * @author kaysaith
 * @date 2023/1/4
 */

export const fileExtension: { [mimeType: string]: string } = {
  ['image/bmp']: 'bmp',
  ['image/cis-cod']: 'cod',
  ['image/gif']: 'gif',
  ['image/ief']: 'ief',
  ['image/jpeg']: 'jpg',
  ['image/pipeg']: 'jfif',
  ['image/svg+xml']: 'svg',
  ['image/tiff']: 'tiff',
  ['image/x-cmu-raster']: 'ras',
  ['image/x-cmx']: 'cmx',
  ['image/x-icon']: 'ico',
  ['image/x-portable-anymap']: 'pnm',
  ['image/x-portable-bitmap']: 'pbm',
  ['image/x-portable-graymap']: 'pgm',
  ['image/x-portable-pixmap']: 'ppm',
  ['image/x-rgb']: 'rgb',
  ['text/css']: 'css',
  ['text/html']: 'html',
  ['video/mp4']: 'mp4',
  ['video/quicktime']: 'mov',
  ['audio/mpeg']: 'mp3',
  ['audio/x-wav']: 'wav',
  ['audio/x-aiff']: 'aif',
  ['application/zip']: 'zip',
  ['application/x-gzip']: 'gz',
  ['application/x-compressed']: 'tgz',
  ['application/msword']: 'doc',
  ['application/pdf']: 'pdf',
  ['application/vnd.ms-powerpoint']: 'ppt',
  ['text/plain']: 'txt',
  ['image/webp']: 'webp',
  ['audio/x-m4a']: 'm4a',
  ['audio/ogg']: 'ogg',
  ['application/rtf']: 'rtf',
  ['application/vnd.openxmlformats-officedocument.wordprocessingml.document']: 'docx',
  ['application/vnd.ms-excel']: 'xls',
  ['image/png']: 'png',
  ['video/webm']: 'webm',
  ['video/x-msvideo']: 'avi',
  ['video/x-m4v']: 'm4v',
  ['application/x-rar-compressed']: 'rar',
}
